# Make sure to check the documentation at http://goreleaser.com
version: 2
env:
  - GO_VERSION=1.22
before:
  hooks:
    - make mod
    - bash build/scripts/wintun.sh
builds:
  - id: "ktctl"
    main: ./cmd/ktctl/main.go
    binary: ktctl
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - 386
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
  - id: "shadow"
    main: ./cmd/shadow/main.go
    binary: shadow
    goos:
      - linux
    goarch:
      - amd64
  - id: "router"
    main: ./cmd/router/main.go
    binary: router
    goos:
      - linux
    goarch:
      - amd64
  - id: "navigator"
    main: ./cmd/navigator/main.go
    binary: navigator
    goos:
      - linux
    goarch:
      - amd64
dockers:
  - goos: linux
    goarch: amd64
    use: buildx
    ids:
      - shadow
    image_templates:
      - "ghcr.io/lujiajing1126/kt-connect/kt-connect-shadow:latest"
      - "ghcr.io/lujiajing1126/kt-connect/kt-connect-shadow:{{ .Tag }}"
      - "ghcr.io/lujiajing1126/kt-connect/kt-connect-shadow:v{{ .Major }}"
    dockerfile: build/docker/shadow/Dockerfile
    skip_push: false
    extra_files:
      - build/docker/shadow/run.sh
      - build/docker/shadow/disconnect.sh
  - goos: linux
    goarch: amd64
    use: buildx
    ids:
      - router
    image_templates:
      - "ghcr.io/lujiajing1126/kt-connect/kt-connect-router:latest"
      - "ghcr.io/lujiajing1126/kt-connect/kt-connect-router:{{ .Tag }}"
      - "ghcr.io/lujiajing1126/kt-connect/kt-connect-router:v{{ .Major }}"
    dockerfile: build/docker/router/Dockerfile
    skip_push: false
    extra_files:
      - build/docker/router/nginx.conf
  - goos: linux
    goarch: amd64
    use: buildx
    ids:
      - navigator
    image_templates:
      - "ghcr.io/lujiajing1126/kt-connect/kt-connect-navigator:latest"
      - "ghcr.io/lujiajing1126/kt-connect/kt-connect-navigator:{{ .Tag }}"
      - "ghcr.io/lujiajing1126/kt-connect/kt-connect-navigator:v{{ .Major }}"
    dockerfile: build/docker/navigator/Dockerfile
    skip_push: false
    extra_files:
      - build/docker/navigator/setup_iptables.sh
archives:
  - id: ktctl
    builds:
      - ktctl
    name_template: >-
      {{- .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else if eq .Arch "arm64" }}arm_64
      {{- else }}{{ .Arch }}{{ end }}
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - src: >-
          artifacts/
          {{- title .Os }}/
          {{- if eq .Arch "amd64" }}x86_64
          {{- else if eq .Arch "386" }}i386
          {{- else if eq .Arch "arm64" }}arm_64
          {{- else }}{{ .Arch }}{{ end }}/*
        dst: .
        strip_parent: true
checksum:
  name_template: '{{ .Tag }}_checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^config:'
      - '^refactor:'
release:
  github:
    owner: lujiajing1126
    name: kt-connect
  ids:
    - ktctl
  # @see https://github.com/goreleaser/goreleaser/issues/1023
  draft: false
  prerelease: auto
