name: ci

on:
  push:
  pull_request:
    branches: [ master ]

jobs:

  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache-dependency-path: "**/*.sum"
      - name: Install dependencies
        run: go get .

      - name: KinD (Kubernetes in Docker) Action
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v0.24.0"

      - name: Test KinD
        run: |
          kubectl cluster-info
          kubectl get pods -n kube-system
          echo "current-context:" $(kubectl config current-context)
          echo "environment-kubeconfig:" ${KUBECONFIG}

      - name: Run unit test
        run: make test

  build-cli:
    name: Build binaries
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache-dependency-path: "**/*.sum"
      - name: Install dependencies
        run: go get ./...

      - name: Run go releaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: 'latest'
          args: --snapshot --skip-publish --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
